# Generated by Django 5.0 on 2023-12-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newssite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(upload_to="covers/"),
        ),
    ]
