# Generated by Django 5.0 on 2023-12-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newssite", "0002_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
